version: "3"
services:
  redis:
    image: redis:5-alpine
    expose:
      - "6379"
  mysql:
    image: mysql:5.7.24
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123123
    volumes:
      - "/media/kavin/新加卷1/deepin/project/auction/data/:/var/lib/mysql"
  php:
    image: php:7.2.12-fpm-alpine
    expose:
      - "9000"
    volumes:
      - "/media/kavin/新加卷1/deepin/project/auction/aucApi/:/var/www/html"
  es:
    image: elasticsearch:6.5.2
    ports:
      - "9200:9200"
      - "9300:9300"
  ki:
    image: kibana:6.5.2
    ports:
      - "5601:5601"
    depends_on:
      - es
    links:
      - es
  nginx:
    image: nginx:1.15.7-alpine
    ports:
      - "1080:80"
    volumes:
      - "/media/kavin/新加卷1/deepin/project/auction/aucApi/:/usr/share/nginx/html"
    links:
      - php:php
      - es:es
      - mysql:mysql
      - redis:redis


